
name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0, 7.4]
        os: [ubuntu-latest]

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysqli, pdo_mysql, bcmath, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest
      - name: Execute CS check
        env: 
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: vendor/bin/php-cs-fixer fix --dry-run
      - name: Execute tests
        env:
          HUBSPOT_API_KEY: ${{secrets.HUBSPOT_KEY}}
        run: vendor/bin/phpunit